#! /bin/bash

LIMIT=10
for i in $(seq 1 $LIMIT); do
  printf "\n"
  echo "---------- Starting Run # $i of $LIMIT----------"
  printf "\n"
  $@
  if [[ $? -eq 1 ]]
  then
    break
  fi

  printf "\n"
  echo "🟢 $i of $LIMIT run(s) successful"
  printf "\n"
done
